const sample=[['Centre de santé Kintambo', -4.341, 15.281, 42000],['Hôpital général de Kinshasa',-4.327,15.313,68000],['Clinique Ngaliema',-4.328,15.268,31500],['CS Référence Limete',-4.356,15.327,24700],['Hôpital Saint Joseph',-4.366,15.291,18300],['Centre de santé Matete',-4.386,15.354,27900]];
let facilities=[], selectedTime=30, markers=[], circles=[], realResults=null;
const map=L.map('map',{zoomControl:false}).setView([-4.349,15.31],12);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);
function format(n){return new Intl.NumberFormat('fr-FR').format(Math.round(n))}
function loadRows(rows, fileLabel='Exemple · Kinshasa.csv'){
 facilities=rows.map((r,i)=>({name:r[0]||`Établissement ${i+1}`,lat:+r[1],lng:+r[2],base:+r[3]||Math.round(12000+Math.random()*55000),id:i})).filter(r=>Number.isFinite(r.lat)&&Number.isFinite(r.lng));
 document.getElementById('file-name').textContent=fileLabel; render(); if(facilities.length) map.fitBounds(facilities.map(f=>[f.lat,f.lng]),{padding:[35,35]});
}
function estimate(f){if(realResults&&realResults[f.name]&&realResults[f.name][selectedTime]!==undefined)return realResults[f.name][selectedTime];const factor={15:.42,30:.72,45:.88,60:1}[selectedTime];return f.base*factor}
function render(){markers.forEach(m=>m.remove());circles.forEach(c=>c.remove());markers=[];circles=[]; const tbody=document.getElementById('facility-table');const q=document.getElementById('search').value.toLowerCase();let shown=facilities.filter(f=>f.name.toLowerCase().includes(q));
 facilities.forEach(f=>{const val=estimate(f);const circle=L.circle([f.lat,f.lng],{radius:selectedTime*70,color:'#69b994',weight:1.5,fillColor:'#9fe0bd',fillOpacity:.17}).addTo(map);circles.push(circle);const marker=L.circleMarker([f.lat,f.lng],{radius:7,color:'#fff',weight:2,fillColor:'#ee8060',fillOpacity:1}).addTo(map).bindPopup(`<div class="popup-name">${f.name}</div><div class="popup-pop">${format(val)} personnes accessibles</div>`);markers.push(marker)});
 const total=facilities.reduce((a,f)=>a+estimate(f),0), avg=facilities.length?total/facilities.length:0;document.getElementById('total-pop').textContent=facilities.length?format(total):'—';document.getElementById('average-pop').textContent=facilities.length?format(avg):'—';document.getElementById('facility-count').textContent=facilities.length;document.getElementById('coverage').textContent=facilities.length?'41 % de la population couverte':'— de la population couverte';document.getElementById('time-label').textContent=`en ${selectedTime} min`;
 tbody.innerHTML=shown.length?shown.map(f=>{const val=estimate(f), pct=Math.min(98,Math.round(val/700));return `<tr><td>${f.name}</td><td>${f.lat.toFixed(3)}, ${f.lng.toFixed(3)}</td><td class="pop">${format(val)}</td><td><span class="bar"><i style="width:${pct}%"></i></span>${pct}%</td></tr>`}).join(''):`<tr class="empty"><td colspan="4">Aucun établissement trouvé.</td></tr>`;
}
document.querySelectorAll('.time-options button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.time-options .active').classList.remove('active');btn.classList.add('active');selectedTime=+btn.dataset.time;render()}));
document.getElementById('load-sample').addEventListener('click',()=>loadRows(sample));document.getElementById('run-analysis').addEventListener('click',render);document.getElementById('search').addEventListener('input',render);
document.getElementById('csv-file').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const lines=reader.result.trim().split(/\r?\n/).slice(1);const rows=lines.map(line=>line.split(/[,;\t]/).map(v=>v.trim().replace(/^"|"$/g,''))).filter(r=>r.length>=3);loadRows(rows,file.name)};reader.readAsText(file)});
document.getElementById('zoom-in').onclick=()=>map.zoomIn();document.getElementById('zoom-out').onclick=()=>map.zoomOut();document.getElementById('locate').onclick=()=>facilities.length&&map.fitBounds(facilities.map(f=>[f.lat,f.lng]),{padding:[35,35]});
document.getElementById('export-csv').onclick=()=>{const header='etablissement,latitude,longitude,personnes_accessibles,temps_minutes\n';const body=facilities.map(f=>`"${f.name.replaceAll('"','""')}",${f.lat},${f.lng},${Math.round(estimate(f))},${selectedTime}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([header+body],{type:'text/csv'}));a.download=`access-care-${selectedTime}min.csv`;a.click()};
loadRows(sample);
// En production, le fichier généré par scripts/compute_access.py prend automatiquement la place de l'exemple.
fetch('public/results.json').then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(!data.facilities)return;realResults=Object.fromEntries(data.facilities.map(f=>[f.name,f.access]));loadRows(data.facilities.map(f=>[f.name,f.latitude,f.longitude,0]),'Résultats réels · WorldPop');}).catch(()=>{});